### ISSUE TITLE
`GLIBC_2.28' not found

### ISSUE THREAD

**Issue by SimonCL17** [raphael-prevost/netron-export#1]
Hi there,

First of all, thank you for creating this tool. I cannot find anything that allows me to convert an onnx model to an image which is really annoying when trying visually show the file in anything that is not an ONNX viewer.

I have tried to run the following command:

netron_export --output ./output.svg ./yolo_nas_s.onnx

but I get the following:

(ONNX_to_Image) simon@simon:~/Documents/ONNX_to_PNG/netron-export$ netron_export --output ./output.svg ./yolo_nas_s.onnx 
Serving './yolo_nas_s.onnx' at http://127.0.0.1:8487
/home/simon/anaconda3/envs/ONNX_to_Image/lib/python3.8/site-packages/playwright/driver/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/simon/anaconda3/envs/ONNX_to_Image/lib/python3.8/site-packages/playwright/driver/node)
Exception: Connection closed while reading from the driver
Stopping http://127.0.0.1:8487
Task exception was never retrieved
future: <Task finished name='Task-4' coro=<Connection.run.<locals>.init() done, defined at /home/simon/anaconda3/envs/ONNX_to_Image/lib/python3.8/site-packages/playwright/_impl/_connection.py:268> exception=Exception('Connection closed while reading from the driver')>
Traceback (most recent call last):
  File "/home/simon/anaconda3/envs/ONNX_to_Image/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 269, in init
    self.playwright_future.set_result(await self._root_object.initialize())
  File "/home/simon/anaconda3/envs/ONNX_to_Image/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 211, in initialize
    await self._channel.send(
  File "/home/simon/anaconda3/envs/ONNX_to_Image/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "/home/simon/anaconda3/envs/ONNX_to_Image/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 482, in wrap_api_call
    return await cb()
  File "/home/simon/anaconda3/envs/ONNX_to_Image/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 97, in inner_send
    result = next(iter(done)).result()
  File "/home/simon/anaconda3/envs/ONNX_to_Image/lib/python3.8/site-packages/netron_export/_netron_export_graph.py", line 23, in save_model_graphs
    async with async_playwright() as pw:
  File "/home/simon/anaconda3/envs/ONNX_to_Image/lib/python3.8/site-packages/playwright/async_api/_context_manager.py", line 47, in __aenter__
    playwright = AsyncPlaywright(next(iter(done)).result())
Exception: Connection closed while reading from the driver
(ONNX_to_Image) simon@simon:~/Documents/ONNX_to_PNG/netron-export$

I have following:

node version: v16.20.2
nvm 0.39.2
Ubuntu 18.04.6 LTS - Bionic

Do you have any suggestions?

All the best,

Simon

**Comment by IljaManakov** [comment]
It's been over a year so I am not sure whether this well help you or not but it might help someone else facing the same issue in the future.
The problem you have is not directly related to this package. Rather it seems that Node.js, which is used as a driver by playwright (one of the dependencies of this package), requires a libc version of 2.28. As you are on Ubuntu 18.04 you probably have 2.27 and it is really not easy to upgrade these kinds of system libs without bricking your OS.

Here are two options that might fix the issue:

1.  It seems like older versions of node might work with older versions of libc. Version 16 in particular seems to do the trick (see [here](https://stackoverflow.com/questions/72921215/getting-glibc-2-28-not-found))

2. Upgrade your Ubuntu distro. Newer Ubuntu versions come with newer libc versions. Also 18.04 is EOL anyway so its probably a good time to upgrade regardless.
